[tools]
"cargo:cargo-nextest" = "latest"
"cargo:sem-cli" = "latest"
rust = { version = "latest", components = "rust-analyzer" }

[tasks.test]
run = '''cargo nextest run'''

[tasks.test-no-fail]
run = '''cargo nextest run --no-fail-fast'''
